# Generated by Django 3.0.7 on 2020-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductName', models.CharField(max_length=300)),
                ('Barcode', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('CostPrice', models.PositiveIntegerField()),
                ('SellingPrice', models.PositiveIntegerField()),
                ('MeasuringUnit', models.CharField(choices=[('Number', 'Number'), ('Kg', 'Kg')], default='Number', max_length=10)),
                ('QuantityAvilable', models.PositiveIntegerField()),
                ('TotalQuantity', models.PositiveIntegerField(default=0, editable=False)),
                ('total', models.PositiveIntegerField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
