# Generated by Django 3.0.7 on 2020-06-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_products_total2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='total2',
        ),
    ]
